# Generated by Django 4.1.7 on 2023-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'tg пользователь', 'verbose_name_plural': 'tg пользователи'},
        ),
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
